[package]
name = "starsource-comparer"
version = "0.5.0"
authors = ["Dennis Duda <git@seri.tools>"]
edition = '2018'

[dependencies]
zydis = "3.0.0"
notify = "4"
clap = "2"
regex = "1.8.3"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
pdb-addr2line = "0.10.4"
thiserror = "1.0"
itertools = "0.10.5"
